import {readFile,readdir,stat} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import path from 'node:path';
import {parseOptions,loadVersion,inside,outputIdentity,readJson,saveJson} from './project.mjs';
import {rendererFiles} from './renderer.mjs';
const o=parseOptions(process.argv.slice(2)),v=await loadVersion(o.project,o.version),m=v.manifest;
if(m.status!=='draft'||m.variants.some(x=>x.output))throw Error('Register only a draft version with no registered outputs');
const hash=async file=>createHash('sha256').update(await readFile(file)).digest('hex');
const runs=[];for(const file of await readdir(path.join(v.directory,'runs')))if(file.endsWith('.json'))runs.push(await readJson(path.join(v.directory,'runs',file)));
const audio=inside(v.projectDirectory,m.inputs.audio.path),audioHash=file=>execFileSync('ffmpeg',['-v','error','-i',file,'-map','0:a:0','-c:a','copy','-f','hash','-hash','sha256','-'],{encoding:'utf8'}).trim();
if(await hash(audio)!==m.inputs.audio.sha256)throw Error('Source audio changed');const expectedAudio=audioHash(audio),rendererHash=await hash(inside(v.directory,m.renderer.path)),files=await rendererFiles(v);
const sourceProbe=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-of','json',audio],{maxBuffer:1e6})).streams.find(s=>s.codec_type==='audio');
if(m.settings.target_frames!==Math.ceil(Number(sourceProbe.duration)*m.settings.fps))throw Error('Target frames do not cover the actual full source audio');
const variants=[];
for(const variant of m.variants){const identity=outputIdentity(m,variant),file=inside(v.directory,identity.path),digest=await hash(file);
 const receipt=runs.find(r=>r.status==='completed'&&r.purpose==='full-render'&&r.project_id===m.project_id&&r.version===m.version&&r.renderer_sha256===rendererHash&&r.audio_sha256===m.inputs.audio.sha256&&r.outputs.some(out=>out.variant===variant.id&&out.path===identity.path&&out.sha256===digest));
 if(!receipt)throw Error('No matching successful render receipt for '+variant.id);
 if(JSON.stringify(receipt.settings)!==JSON.stringify(m.settings)||JSON.stringify(receipt.request)!==JSON.stringify(m.request)||receipt.treatment_sha256!==await hash(path.join(v.directory,'TREATMENT.md')))throw Error('Version treatment or parameters changed after render');
 if(JSON.stringify(receipt.renderer_files)!==JSON.stringify(files))throw Error('Renderer dependency changed after render');
 if(JSON.stringify(Object.keys(receipt.data_hashes).sort())!==JSON.stringify(Object.keys(m.data).sort()))throw Error('Data mapping changed after render');
 for(const [key,digest] of Object.entries(receipt.data_hashes))if(await hash(inside(v.directory,m.data[key]))!==digest)throw Error('Data changed after render');
 const p=JSON.parse(execFileSync('ffprobe',['-v','error','-count_frames','-show_streams','-show_format','-of','json',file],{maxBuffer:1e7})),s=p.streams.find(x=>x.codec_type==='video');
 if(!s||s.width!==m.settings.width||s.height!==m.settings.height||s.avg_frame_rate!==`${m.settings.fps}/1`||Number(s.nb_read_frames)!==m.settings.target_frames)throw Error('Output specification mismatch');
 if(Math.abs(Number(s.duration)-Number(sourceProbe.duration))>=1/m.settings.fps)throw Error('Picture and full source audio duration differ by at least one frame');
 if(audioHash(file)!==expectedAudio)throw Error('Output audio changed');execFileSync('ffmpeg',['-v','error','-i',file,'-f','null','-'],{stdio:['ignore','ignore','pipe']});
 variants.push({...variant,output:{path:identity.path,sha256:digest,size_bytes:(await stat(file)).size,duration_seconds:Number(s.duration),codec:s.codec_name,width:s.width,height:s.height,frame_rate:s.avg_frame_rate,frame_count:Number(s.nb_read_frames),audio_packet_hash:expectedAudio,status:'review',run_id:receipt.id}});
 await saveJson(path.join(v.directory,'runs',variant.generation_id+'-ffprobe.json'),p);
}
m.variants=variants;m.status='review';m.renderer.sha256=rendererHash;m.renderer.files=files;m.validation={full_decode:'passed',source_audio_packets:'identical',registered_at:new Date().toISOString(),human_review:'pending'};await saveJson(path.join(v.directory,'manifest.json'),m);console.log('Registered',m.project_id,m.version,'as review');
